### ISSUE TITLE
Not compatible with Python3 anymore

### ISSUE THREAD

**Issue by jlebonzec** [adamziel/django_translate#5]
Hello @adamziel ,

I don't know which version of Python you aimed to support, but it seems that the last commit introduced an incompatibility with Python3:

```
    File "/usr/lib/python3.6/site-packages/django_translate/middleware.py", line 5
    except ImportError, e:
                      ^
SyntaxError: invalid syntax
```

It most likely comes to this line.
https://github.com/adamziel/django_translate/blame/master/django_translate/middleware.py#L5

After some testing, it seems that the `as` syntax is also compatible with python 2.7:
```
$ python2.7
Python 2.7.13 (default, Jul 21 2017, 03:24:34)
[GCC 7.1.1 20170630] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> try:
...     raise ValueError("this works")
... except ValueError as e:
...     print e
...
this works
```

I created a PR (#6) proposing a fix

**Comment by straxus** [comment]
I can confirm that I see the same issue (Invalid syntax), using Python 3.5.2 - the attached PR fixes the issue for me when I apply the change locally.

**Comment by adamziel** [comment]
Merged and released to pip. Thank you guys!
